version: '3'
services:
  airflow:
    image: apache/airflow:latest
    restart: always
    environment:
      - AIRFLOW_CORE_EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
